### ISSUE TITLE
是否应该允许使用自定义 uuid ？

### ISSUE THREAD

**Issue by hyony** [Awhisper/VKKeychainIDFV#1]
你好，使用这段代码时，发现有个问题。我们的老版本原先已经生成了一个 uuid， 但是并不是直接使用的 `identifierForVendor`。使用您的代码之后，为了在版本升级时保持之前的 uuid 不变，我需要改动你的代码。
如果这个库的目的就是让人们更方便的使用 `identifierForVendor`，那现在的接口确实比较好用。但如果做以下调整，可能会更通用一些，建议考虑。

```
+(NSString *)recommendedIDFV;

-(BOOL)saveVKKeychainIDFV:(NSString *)IDFVString;
+(BOOL)saveVKKeychainIDFV:(NSString *)IDFVString;

-(void)removeVKKeychainIDFV;
+(void)removeVKKeychainIDFV;

```

**Comment by Awhisper** [comment]
@hyony IDFV其实是一个明确的值，并且是只读的不可写的，我能理解你的需求，你其实是想写入自己定义的值，但这个值就不是IDFV了，你需要的是拆解keychain部分的代码功能去做你想要的 keychainCustomUUID（相关读写keychain的工具也有很多开源的），而不是让我这个定位在纯IDFV上的工具，进行接口扩充
